package com.uw.watcarpool.server;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;

import javax.mail.MessagingException;

import com.googlecode.objectify.Query;
import com.google.appengine.api.datastore.QueryResultIterator;
import com.google.appengine.api.users.User;
import com.google.appengine.api.users.UserService;
import com.google.appengine.api.users.UserServiceFactory;
import com.google.gwt.i18n.client.DateTimeFormat;
import com.google.gwt.user.client.Window;
import com.google.gwt.user.server.rpc.RemoteServiceServlet;
import com.googlecode.objectify.Objectify;
import com.googlecode.objectify.ObjectifyService;
import com.uw.watcarpool.client.Booking;
import com.uw.watcarpool.client.DataStoreService;
import com.uw.watcarpool.client.Deal;
import com.uw.watcarpool.client.Driver;
import com.uw.watcarpool.client.Match;
import com.uw.watcarpool.client.Passenger;
import com.uw.watcarpool.shared.Emailer;


@SuppressWarnings("serial")
public class DataStoreServiceImpl extends RemoteServiceServlet implements
		DataStoreService {

	static{
		ObjectifyService.register(Match.class);
	    ObjectifyService.register(Passenger.class);
	    ObjectifyService.register(Driver.class);
	    ObjectifyService.register(Deal.class);
		}
	Emailer emailer = new Emailer();
	
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public List<Driver> checkDrivers(String kind, String name, String contact, Date date, String pickupLoc, String dropoffLoc, int spots,  String comment) throws IllegalArgumentException {
		UserService userService = UserServiceFactory.getUserService();
	    User user = userService.getCurrentUser();
        Objectify ofy = ObjectifyService.begin();
        List<Driver> ret = new ArrayList<Driver>();
		
        // First level filters
        Query<Driver> q = ofy.query(Driver.class).filter("_spots >=", spots).filter("_dropoffLoc", dropoffLoc.toUpperCase().trim()).filter("_pickupLoc", pickupLoc.toUpperCase().trim());
		QueryResultIterator<Driver> iterator = q.iterator();

		// Second level filters	
		while (iterator.hasNext()) {
	        Driver d = iterator.next();
	        if ((d._date.after(date) || d._date.equals(date))&&!d._pending)
	        {
	         ret.add(d);
	        }

		}
        
		// Insert into the corresponding database first

    	Passenger passenger = new Passenger(contact, date, pickupLoc.toUpperCase(), dropoffLoc.toUpperCase(), spots, user.getEmail().toLowerCase(), comment);
    	assert passenger._UUID != null;    // id was autogenerated
    	ofy.put(passenger);
		
		// Return the filtered results to the client
	    if (ret.size()!=0)
	    {
	    	// Sort the output list according to date.
	    	Collections.sort(ret, new Comparator(){ 
	    		public int compare(Object d1, Object d2){    		       
	    	        Date d1Date = ((Driver)d1)._date;        
	    	        Date d2Date = ((Driver)d2)._date;	    	       
	    	        if(d1Date.after(d2Date))
	    	            return 1;
	    	        else if(d1Date.before(d2Date))
	    	            return -1;
	    	        else
	    	            return 0;    
	    	    }
	    	});
	    	

	    	return ret;
	    	
	    }
	    else // Create a new entry in the database 
	    {
	    	return null;
	    	
	    }
		    
	}
	

	public List<Passenger> checkPassengers(String kind, String name, String contact, Date date, String pickupLoc, String dropoffLoc, int spots, int price, String comment)
		{
		UserService userService = UserServiceFactory.getUserService();
	    User user = userService.getCurrentUser();
		Objectify ofy = ObjectifyService.begin();
        List<Passenger> ret = new ArrayList<Passenger>();
		 
        // First level filters
        Query<Passenger> q = ofy.query(Passenger.class).filter("_spots <=", spots).filter("_dropoffLoc", dropoffLoc.toUpperCase().trim()).filter("_pickupLoc", pickupLoc.toUpperCase().trim());
		QueryResultIterator<Passenger> iterator = q.iterator();

		// Second level filters	
		while (iterator.hasNext()) {
	        Passenger p = iterator.next();
	        if (p._date.equals(date)&&!p._pending)
	        {
	         ret.add(p);
	        }

		}
        // Insert into the corresponding database first
		Driver driver = new Driver(contact, date, pickupLoc.toUpperCase(), dropoffLoc.toUpperCase(), spots, user.getEmail().toLowerCase(), price, comment);
    	assert driver._UUID != null;    // id was autogenerated
    	ofy.put(driver);
		// Return the filtered results to the client
	    if (ret.size()!=0)
	    {
	    	return ret;
	    	
	    }
	    else
	    { 	
	    	return null;
	    }
	}
	
    public String updateDrivers(String dUUID, Date date, String userId, String dropoffLoc, String contact)
    {
    	String ret=null;
        Objectify dofy = ObjectifyService.begin();
    	Driver d = dofy.get(Driver.class, new Long(dUUID));  
    	
    	Objectify pofy = ObjectifyService.begin();
    	Query<Passenger> q = pofy.query(Passenger.class).filter("_userId", userId).filter("_dropoffLoc", dropoffLoc).filter("_contact", contact.trim());
    	
    	QueryResultIterator<Passenger> iterator = q.iterator();
		while (iterator.hasNext()) {
	        Passenger p = iterator.next();
	        if (p._date.equals(date))
	        {
	        	// Update parameters for each party
	        	d._spots=d._spots-p._spots;
	        	p._pending=true;
	        	if(d._spots==0)
	        	{
	        		d._pending=true;
	        	}
	        	dofy.put(d);
	        	pofy.put(p);
	        	Objectify mfy = ObjectifyService.begin();
	        	Match m = new Match(d._UUID, p._UUID, p._userId);
	        	assert m._UUID != null;
	        	mfy.put(m);
	        	// Notify the selected driver
	        	try {
	        		StringBuilder sb=new StringBuilder();
	        		sb.append("Dear "+d._contact+":\n");
	        		sb.append("You have a new pending booking for your carpool on "+d._date.toString()+"\n");
	        		sb.append("Passenger Contact #: "+p._contact+"\n");
	        		sb.append("Dropoff Region: "+p._dropoffLoc+"\n");
	        		sb.append("Message: "+p._detail+"\n");
	        		sb.append("Please login to http://watcarpool.appspot.com to confirm/decline the booking\n");
	        		sb.append("\n");
	        		sb.append("\n");
	        		sb.append("From Watcarpool");
					emailer.sendEmail("New Pending Booking - Watcarpool",sb.toString(), d._userId);
				} catch (UnsupportedEncodingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	        	ret=m._UUID.toString();
	        }
		}
		return ret;
		
    }
    
    public String updatePassengers(String pUUID, Date date, String userId, String dropoffLoc, String contact)
    {
    	
    	String ret=null;
        Objectify pofy = ObjectifyService.begin();
    	Passenger p = pofy.get(Passenger.class, new Long(pUUID));  
    	
    	Objectify dofy = ObjectifyService.begin();
    	Query<Driver> q = dofy.query(Driver.class).filter("_userId", userId).filter("_dropoffLoc", dropoffLoc).filter("_contact", contact.trim());
    	QueryResultIterator<Driver> iterator = q.iterator();
		while (iterator.hasNext()) {
	        Driver d = iterator.next();
	        if (d._date.equals(date))
	        {
	        	// Update parameters for each party
	        	d._spots=d._spots-p._spots;
	        	p._pending=true;
	        	if(d._spots==0)
	        	{
	        		d._pending=true;
	        	}
	        	dofy.put(d);
	        	pofy.put(p);
	        	Objectify mfy = ObjectifyService.begin();
	        	Match m = new Match(d._UUID, p._UUID, d._userId);
	        	assert m._UUID != null;
	        	mfy.put(m);
	        	// Notify the selected driver
	        	try {
	        		StringBuilder sb=new StringBuilder();
	        		sb.append("Dear "+d._contact+":\n");
	        		sb.append("You have a new pending booking for your carpool request on "+p._date+"\n");
	        		sb.append("Driver Contact #: "+p._contact+"\n");
	        		sb.append("Dropoff Region: "+p._dropoffLoc+"\n");
	        		sb.append("Details: "+p._detail+"\n");
	        		sb.append("Please login to http://watcarpool.appspot.com to confirm/decline the booking\n");
	        		sb.append("\n");
	        		sb.append("\n");
	        		sb.append("From Watcarpool");
					emailer.sendEmail("New Pending Booking - Watcarpool",sb.toString(), p._userId);
				} catch (UnsupportedEncodingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
	        	ret=m._UUID.toString();
	        }
		}
		return ret;
		
    }
    
    public List<Booking> getBookings(String email)
	{
    	List<Booking> myBookings =new ArrayList<Booking>();
     	Objectify mfy = ObjectifyService.begin();
    	Objectify dofy = ObjectifyService.begin();
    	Objectify pofy = ObjectifyService.begin();
    	
    	Query<Match> q = mfy.query(Match.class);
    	QueryResultIterator<Match> iterator = q.iterator();
    	
    	while (iterator.hasNext()) {
    		Match m = iterator.next();
    		Driver d = dofy.get(Driver.class, m._driver);
    		Passenger p = pofy.get(Passenger.class,m._passenger);
    	    if (d._userId.equalsIgnoreCase(email) || p._userId.equalsIgnoreCase(email))
    	    {
    	    	myBookings.add(new Booking(m._UUID.toString(), d,p, m._bookerEmail));
    	    }
    	}
    	return myBookings;
	
	}
    
    @SuppressWarnings("deprecation")
	public String deleteBooking(String matchId, boolean isDeal)
	{
    	String ret=null;
     	Objectify mfy = ObjectifyService.begin();
    	Objectify dofy = ObjectifyService.begin();
    	Objectify pofy = ObjectifyService.begin();
    	Objectify deofy = ObjectifyService.begin();
    	
    	Match m = mfy.get(Match.class, new Long(matchId));
    	Driver d= dofy.get(Driver.class,m._driver);

    	Passenger p = pofy.get(Passenger.class,m._passenger);
    	// Update Available Spots
    	d._numConfirmed=d._numConfirmed+p._spots;   	
    	
    	if (d._numConfirmed==d._capacity)
    	{
    	   dofy.delete(Driver.class,m._driver);
    	}
    	else
    	{
    		dofy.put(d); // Update the corresponding record
    	}
    	if (isDeal)
    	{
    	Deal deal = new Deal(d._date,d._contact,d._userId,p._contact,p._userId,d._dropoffLoc,d._pickupLoc);
    	assert deal._UUID != null;
    	deofy.put(deal);
    	// Send Confirmation Emails to both parties
    	Emailer emailer = new Emailer();
    	StringBuilder sb = new StringBuilder();
    	sb.append("----------Carpool Confirmation Details----------\n");
    	sb.append("Confirmation ID: "+deal._UUID.toString()+"\n");
    	sb.append("Driver Contact: "+d._contact+"\n" );
    	sb.append("Passenger Contact: "+p._contact+"\n");
    	sb.append("Dropoff Region: "+d._dropoffLoc+"\n");
    	sb.append("Pickup Region: "+d._pickupLoc+"\n");
    	sb.append( "Carpool Date/Time: "+d._date.toString()+"\n");
    	sb.append("Price: $"+d._price+"\n");
    	sb.append("Driver's Comments: "+d._detail+"\n");
    	sb.append("Passenger's Comments: "+p._detail+"\n");
    	sb.append("\n");
    	sb.append("\n");
    	sb.append("Thanks for using Watcarpool, have a safe trip!");
    	

			try {
				emailer.sendEmail("Carpool Confirmation("+deal._UUID+")", sb.toString(), d._userId);
				emailer.sendEmail("Carpool Confirmation("+deal._UUID+")", sb.toString(), p._userId);
			} catch (UnsupportedEncodingException e) {
				e.printStackTrace();
			}
			
    	ret=deal._UUID.toString();
    	}
    	pofy.delete(Passenger.class,m._passenger);
    	mfy.delete(Match.class,m._UUID);
    	return ret;
    	
	}
	 
	
}
